### PR TITLE
New layout of the calendar for the time fields #45

### PR DESCRIPTION
**Pull request by brunoramalho**
@gregrickaby please check if it is nice, I applied to all wordpress admin themes

### CODE REVIEW

**Comment by brunoramalho** [comment]
@jtsternberg I updated my fork project and re-sent the pull request

**Comment by jtsternberg** [comment]
Can you check the most recent version and see if this PR is still necessary?

**Comment by brunoramalho** [comment]
Yes I can...

Att.
Bruno Ramalho

​​

2015-04-06 11:58 GMT-03:00 Justin Sternberg <notifications@github.com>:

**Comment by jtsternberg** [comment]
CMB2 date/time-pickers have undergone significant changes since this PR. Hopefully this issue is addressed, but if not, feel free to open a new PR against the trunk branch (as per [contribution guidelines](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md#how-to-contribute-to-cmb2)).

**Pull request closed without merging**
