### PR TITLE
Fixed undefined variable: page_type

### PR DESCRIPTION
**Pull request by anhskohbo**
You're missing $page_type variable :)

### CODE REVIEW

**Comment by tw2113** [comment]
Not quite sure what this is supposed to fix, to be honest. The original version in the line changed would return a value right away. All you're ending up doing is assigning that to a variable, inside an if statement. Never been a fan of variable assignment inside if statements myself.

Is this fixing an open issue at all? or just casual looking over of the code?

**Comment by anhskohbo** [comment]
You can look `$page_type` never declared before.

**Comment by tw2113** [comment]
Gotcha.

**Comment by jtsternberg** [comment]
Thank you sir.

**Comment by anhskohbo** [comment]
You're welcome :)

**Pull request merged**
