### PR TITLE
Update datepicker & timepicker styles & scripts

### PR DESCRIPTION
**Pull request by JonMasterson**
Updated Timepicker utilizing the [@trentrichardson](https://github.com/trentrichardson) jQuery Timepicker addon (https://github.com/trentrichardson/jQuery-Timepicker-Addon) and updated Datepicker styles for aesthetics. User admin color scheme will now effect colors/highlights within the date/timepickers. Reported/requested in ([#204](https://github.com/WebDevStudios/CMB2/issues/204)) and ([#45](https://github.com/WebDevStudios/CMB2/issues/45)).

### CODE REVIEW

**Comment by JonMasterson** [comment]
Screenshots with a couple admin color schemes...

midnightdate
midnighttime
ectotime
ectodate

**Comment by jtsternberg** [comment]
This looks like a really nice addition. Can you be sure to pull/merge from our trunk branch so yours is up-to-date?

**Comment by JonMasterson** [comment]
Done. Let me know if you need anything else. Thanks!

**Comment by jtsternberg** [comment]
There's a ton of file-mode changes that got committed. To clean up, I can either manually merge your stuff in (you'd be removed from the git history), or if you want to try and submit another PR w/ only the relevant files changes (no file-mode changes), I'll take a look at merging again.

**Pull request closed without merging**
