### PR TITLE
CMB2 REST API

### PR DESCRIPTION
**Pull request by jtsternberg**
Individual needs are documented in the [REST API milestone](https://github.com/WebDevStudios/CMB2/milestones/REST%20API)

### CODE REVIEW

**Comment by Mte90** [comment]
any news?

**Comment by Mte90** [comment]
As I can see the 4.6 will improve the support on rest api for meta https://make.wordpress.org/core/2016/07/08/enhancing-register_meta-in-4-6/

**Comment by Mte90** [comment]
Sorry for the comment but I am waiting like a kid under the Christmas tree for this feature.
There is any date for the official integration?

**Comment by tw2113** [comment]
@Mte90 why not pull a copy of trunk and try things out now? Beta test it and report bugs as you try to use it.

**Comment by Mte90** [comment]
Any suggestion for try it? to enable the support maybe is required a flag? any hint to try it?

**Comment by tw2113** [comment]
Dunno on that part, if I were to guess, it'd just be made available automagically, but I haven't paid much attention to the REST API topic in a long time. My hopes would be that the data comes with post request responses out of box with a REST API-ready copy of CMB2.

**Comment by Mte90** [comment]
I added to a field `shot_in_rest => true` but there are no result on the rest api, maybe I am missing something.

**Pull request closed without merging**
