### PR TITLE
Update travis.yml to support PHP 7

### PR DESCRIPTION
**Pull request by tw2113**
TravisCI supports PHP7 as of this: https://github.com/travis-ci/travis-ci/issues/2480#issuecomment-75988205

### CODE REVIEW

**Comment by jtsternberg** [comment]
Hmmm.. tests failed on 7. https://travis-ci.org/WebDevStudios/CMB2/builds/52170940 because `msyql_connect` is removed in 7: http://stackoverflow.com/a/12860046

Hmmm sounds like a WP patch is needed.

**Comment by tw2113** [comment]
Justin, I've been pointed to https://buddypress.trac.wordpress.org/changeset/8392/trunk/.travis.yml for my BuddyPress patch of the same nature, may be worth doing ourselves here.

**Comment by jtsternberg** [comment]
@tw2113 fair, want to update your PR?

**Comment by tw2113** [comment]
Yeah, will do soon, probably at the same time I update my BP patch later.

**Pull request closed without merging**
