### PR TITLE
Wysiwyg.js

### PR DESCRIPTION
**Pull request by jtsternberg**
Creating this PR so others can check out the new feature and test it. Replaces #693.

### CODE REVIEW

**Comment by timburden** [comment]
After updating to the latest trunk I get errors on what was working code. I "think" it's related to this PR.

Here's the code, with a bunch of group fields left out:

```        $module_placements = $cmb->add_field( array(
            'id'          => 'module_placements',
            'type'        => 'group',
            'description' => __( 'Module Placements', 'cmb' ),
            'repeatable' => true,
            'options'     => array(
                'group_title'   => __( 'Module Placement {#}', 'cmb' ),
                'add_button'    => __( 'Add Another Placement', 'cmb2' ),
                'remove_button' => __( 'Remove Placement', 'cmb2' ),
                'sortable'      => false,
                'closed'     => true,
            ),
            'after_group' => array( $this, 'change_group_titles' ),
        ) );

        $cmb->add_group_field( $module_placements, array(
            'name'             => __( 'Label', 'cmb2' ),
            'id'               => 'label',
            'type'             => 'text',
        ) );
....
       $cmb->add_group_field( $module_placements, array(
            'name' => 'Default Modules',
            'description' => 'Enter default modules for this placement here',
            'id'   => 'default_shortcodes',
            'type' => 'wysiwyg',
            'options' => array(
                'wpautop' => false,
                'media_buttons' => false,
                'tinymce' => array(
                    'toolbar1' => 'sjmcm_editor_button',
                ),
                'quicktags' => false,
            ),
        ) );```

The wysiwyg field in the first group is working fine, subsequent groups are broken; and after I add a new group the wysiwyg inside that is broken.

In JS console the error is "Uncaught TypeError: window.quicktags is not a function" in cmb2.min.js

Previously, the wysiwygs were working fine, except that when adding a new group that wysiwyg would be broken until the options page was saved. I am trying the latest to hopefully fix that exact problem.

NOTE: I am also using JS to change the title on the group depending on the label field, almost exactly per [this snippet](https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/javascript/dynamically-change-group-field-title-from-subfield.php).

**Comment by tw2113** [comment]
If I accidentally accepted the merge, my apologies. I was trying to cleanup the code comments. May have clicked the wrong button @jtsternberg

**Comment by timburden** [comment]
This is still not fixed, and has been released I believe. Should I make it an issue?

**Comment by tw2113** [comment]
@jtsternberg Apparently we need to re-review this one, from Tim's comment above.

**Pull request merged**
