### PR TITLE
datepicker and timepicker fixes

### LINKED ISSUE #282: time_format in field type "text_time"
In your Wiki i found this in the example of field "text_time": // 'time_format' => 'h:i:s A',

But when I change the format to 24h like this "H:i" or "G:i" it will not affect anything.
The time_format is always the same..

I hope this feature will be fixed soon, or you can tell me what I'm doing wrong now.

Best regards
Sven

### LINKED ISSUE #300: Date picker problem in auto format dd/mm/Y (pt_BR)
Hello,
I'm using WordPress in pt_BR version. With this the date picker carries been translated into my language, and enter the date in the field in the format dd / mm / Y. And when the post unless the date is not saved when for example the day is greater than 12 , because by default the CMB2 will consider the day as month , and there could not convert the date in the format dd / mm / Y for the timestamp format .

### PR DESCRIPTION
**Pull request by yivi**
Support for `date-format` and `time-format` in text_date and text_time fields. They accept a php formatted string, which is converted to a js formatted string and injected in the data attribute so the pickers can be initialized appropriately.  Fixes #282, fixes #300

### CODE REVIEW

**Comment by jtsternberg** [comment]
Thanks a ton for putting time in to work on this issue. To help me better review your PR, I have a few requests:

* Remove all edits/changes that are not related to this bug-fix/issue
* Remove all white-space changes (same as above). This includes doc-block edits.
* Try to keep your PR as focused on solving a single problem as possible

I like the edits you made (better doc-blocks, etc), but these things should be separate PRs. It's much easier to merge a PR that is simply doc-block edits than one that is changing functionality, or worse, both.

Can you submit separate PRs to split these concerns and make it easier to review/merge? Thank you.

**Comment by yivi** [comment]
Hi there. Will do! 


Sorry about those side tracked changes. Code style happened because I had my ide to auto format to wp guidelines on save and didn't realize, and the docblocks was probably me going over the code inspection notices and warnings before committing. 




I'll make this changes on Monday eve. Regards and have a nice weekend! 





—

**Comment by jtsternberg** [comment]
Ok thanks again! I really do like the formatting cleanup, so feel free to submit another separate PR if you're up for it.

**Comment by yivi** [comment]
I think I removed all formatting changes from the PR.
Let me know if you see something you think it would benefit from a bit more work.

Regards!

**Comment by ryanduff** [comment]
Does this happen to catch the timezone dropdown issues or do I need to open another PR? I looked through and doesn't look like it was mentioned. 

Right now the dropdown works if you use a timezone, but not a UTC offset. Throws a fatal error.

`PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in /cmb2/includes/CMB2_Sanitize.php:269`

**Comment by jtsternberg** [comment]
Thank you for cleaning it up, that helps a ton. Now that I can see what's going on, I see you are using [`DateTime::createFromFormat`](http://php.net/manual/en/datetime.createfromformat.php) which unfortunately is a PHP 5.3 feature. We have to support the same versions of PHP that WordPress does, which is 5.2.4. Maybe you can check if that feature exists and use it and if not, create a fallback solution?

**Comment by yivi** [comment]
5.2... I hope WP Core gets up to speed at some point; 5.2 has been eol for more than 4 years now... and 7 is around the corner. :P

Pushed a new version that checks if create_date_from_format exists, and defines it if not.

Thanks and regards!

**Comment by jtsternberg** [comment]
@yivi Why didn't you update the `text_datetime_timestamp` field type w/ your changes? I'm concerned that the changes you've made are not taking all the field types and/or scenarios into account.

**Comment by jtsternberg** [comment]
Nice work so far. I've merged your branch into trunk and created a new branch. let's collaborate on this branch instead of trunk until it's ready to go: https://github.com/WebDevStudios/CMB2/tree/yivi-date-time-picker-fixes

**Comment by yivi** [comment]
Sorry for the late reply. I was out on holidays on a cycling trip, very
much away from the keyboard.

I'll resume work this week. I'll take a look a at what's left, hopefully we
can have everything wrapped up soon enough.

Regards!



2015-07-29 18:44 GMT+02:00 Justin Sternberg <notifications@github.com>:

**Comment by jtsternberg** [comment]
This is almost good to go. Just need to make sure that all the date type fields are accounted for in this change.

**Comment by jtsternberg** [comment]
@yivi will you be able to add support for ALL the date type fields?

**Comment by tw2113** [comment]
Is there any way we could add in fetching the date_format option from the user's General Settings as a default format value as well?

**Comment by jtsternberg** [comment]
Also, how does this differ from #446?

**Comment by yivi** [comment]
Justin,

I've tried my fixes with all these date/time fields, and they are working:
- text_date_timestamp
<https://github.com/WebDevStudios/CMB2/wiki/Field-Types#text_date_timestamp>
Date Picker (UNIX timestamp)
- text_datetime_timestamp
<https://github.com/WebDevStudios/CMB2/wiki/Field-Types#text_datetime_timestamp>
Text Date/Time Picker Combo (UNIX timestamp)
- text_datetime_timestamp_timezone
<https://github.com/WebDevStudios/CMB2/wiki/Field-Types#text_datetime_timestamp_timezone>
Text Date/Time Picker/Time zone Combo
- text_time
<https://github.com/WebDevStudios/CMB2/wiki/Field-Types#text_time> Time
picker
#446 relates to text_datetime_timestamp_timezone, which is covered, right?

Regards

2015-10-07 17:57 GMT+02:00 Justin Sternberg <notifications@github.com>:

**Comment by yivi** [comment]
Just merged current trunk and tested it on a couple of working sites.

Things look good.

2015-10-08 20:39 GMT+02:00 Yivi <nardus@gmail.com>:

**Comment by yivi** [comment]
Work continued in #446

**Pull request closed without merging**
