### PR TITLE
Add a filter to allow for adding arbitrary HTML attributes to a group…

### PR DESCRIPTION
**Pull request by jrfnl**
… wrapper element.

### CODE REVIEW

**Comment by tw2113** [comment]
@jrfnl may not be a bad idea to put a space before the `$more_attributes` variable to prevent running attributes together. Not quite sure how browsers would handle it, but perhaps better safe than sorry? We should also add attribute escaping for security purposes.

I am curious about the use-cases that you see with this.

@jtsternberg Since this one defaults to an empty string, and is just html attributes, i don't see a huge amount of breakage potential.

**Comment by jtsternberg** [comment]
I'm inclined to move the `CMB2_Types::concat_attrs()` method to `CMB2_Utils`, and use that generate the string of attributes, and have the filter take an array. BUT..  this filter feels a bit arbitrary to me. Is there any reason to do this instead of doing things in JS, which is likely where you'll be wanting to use the extra attributes anyway?

**Comment by jrfnl** [comment]
> Is there any reason to do this instead of doing things in JS, which is likely where you'll be wanting to use the extra attributes anyway?

@jtsternberg This is for the CMB2 Conditionals plugin to allow for conditional groups. The attributes determining the conditions would need to be added for the js to be able to pick up on it.

**Comment by jtsternberg** [comment]
Thanks @jrfnl! Hopefully that helps w/ the CMB2 Conditionals plugin. I've updated the filter to use `concat_attrs`, which means the filter sends an array and requires one back. See the change here: https://github.com/WebDevStudios/CMB2/commit/337c24317f8de88a456f9f3691ace635a2f8dcc5

**Pull request merged**
