### PR TITLE
Fix for #264, repeatable groups with a WYSIWYG editor

### PR DESCRIPTION
**Pull request by johnsonpaul1014**
I believe this fixes the problem by setting up a new editor when the new group row is added.  It is also necessary to destroy and reinit all the editors when sorting.

### CODE REVIEW

**Comment by alexmansfield** [comment]
It looks like custom WYSIWYG buttons (such as the one Gravity Forms adds) don't get attached after the first WYSIWYG field.

**Comment by johnsonpaul1014** [comment]
That's strange.  I have some custom buttons I have added to our editor on the site I needed to implement this change for, and they are added as new editors are added to the group.  Are you using multiple editors in the same group row?

**Comment by alexmansfield** [comment]
I'm not sure if it happens for buttons that are added directly to the TinyMCE editor. I was noticing it for buttons that get added above the editor (next to the "Add Media" button). For example, the Column Shortcodes plugin attaches a button there (other plugins do as well, but that was the first free example I could think of).

**Comment by johnsonpaul1014** [comment]
I did some investigation into this, and it looks like the plugin you are referring to uses the edButtons JavaScript array to add the buttons.  It would probably be possible to clone this somehow for the new editors, but I think that should be left to someone else as I don't need that feature for my current project.  The change is still a huge step forward, because at least you get a real editor and not a broken one when you add a group row.

**Comment by alexmansfield** [comment]
Right, I wasn't trying to put down your improvements at all. Your patch is a huge step forward. I just noticed the missing buttons when testing it out and figured this was probably the place to mention it. I'm sorry if this was the wrong place to mention it. Thanks for the effort you put into this, and keep up the good work!

**Comment by johnsonpaul1014** [comment]
Thanks.  I agree; this is definitely the place to mention it.  Hopefully someone else can grab the baton from here.

**Comment by webakimbo** [comment]
@johnsonpaul1014 would love to use your branch for a time-sensitive project but the build appears to be broken. Is the plugin still working on your end?

**Comment by johnsonpaul1014** [comment]
I forked off master instead of trunk, so that was also an issue.  I am going to make a new pull request off trunk to see if that works this morning.

Paul

Date: Sun, 17 Jul 2016 19:17:33 -0700

**Comment by johnsonpaul1014** [comment]
I have submitted the new pull request.

Paul

Date: Sun, 17 Jul 2016 19:17:33 -0700

**Comment by webakimbo** [comment]
Thanks! Will keep an eye out for activity.

**Comment by tw2113** [comment]
@johnsonpaul1014 are we good to close this one, if you've issued a fresh pull request with updated details?

**Comment by johnsonpaul1014** [comment]
Yes.

**Pull request closed without merging**
