### PR TITLE
update files to be PHP7 compatible

### LINKED ISSUE #719: CMB2 isn't fully PHP 7.0 compliant
### Expected Behavior:

1. Run PHP_CodeSniffer with PHPCompatibility set to 7.0 
    `phpcs --standard=PHPCompatibility --runtime-set testVersion 7.0`
    Or, run a report using the plugin [php-compatibility-checker](http://wordpress.org/plugins/php-compatibility-checker)

* Get a clean report with no notices, warnings, or errors

### Actual Behavior:

1. Run PHP_CodeSniffer with PHPCompatibility set to 7.0
    Or, run a report using the plugin [php-compatibility-checker](http://wordpress.org/plugins/php-compatibility-checker)

* Get the following output

Name: CMB2

```
FILE: ... /wp-content/plugins/cmb2/css/index.php
------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------
 1 | WARNING | No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.
------------------------------------


FILE: .../wp-content/plugins/cmb2/images/index.php
------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------
 1 | WARNING | No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.
------------------------------------


FILE: .../wp-content/plugins/cmb2/includes/CMB2_Field.php
----------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------
 1054 | ERROR | Function name, class name, namespace name or constant name can not be reserved keyword 'string' (since version 7.0)
----------------------------------------------------------


FILE: .../wp-content/plugins/cmb2/includes/CMB2_Types.php
-------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------
 133 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)
-------------------------------------------------


FILE: .../wp-content/plugins/cmb2/includes/index.php
------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------
 1 | WARNING | No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.
------------------------------------


FILE: .../wp-content/plugins/cmb2/index.php
------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------
 1 | WARNING | No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.
------------------------------------


FILE .../wp-content/plugins/cmb2/js/index.php
------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------
 1 | WARNING | No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.
------------------------------------
```

### PR DESCRIPTION
**Pull request by ryanshoover**
Fixes #719 .

### Changes proposed in this pull request

-  Add <?php opening tag to empty php files

-  Rename `CMB_Field->string()` function to `CMB_Field->get_string()` (string is a reserved keyword in PHP 7.0)

### CODE REVIEW

**Comment by tw2113** [comment]
Looks good to me, for the most part. Ran ack on the code and you covered any cases of using the "string()" method, however others who may be using that method will need to update as well. Only real blocker I can find.

Up to Justin to approve though.

**Comment by jtsternberg** [comment]
Merged. I've added a back-compat shim if anyone is using the `string` method: https://github.com/WebDevStudios/CMB2/commit/b0792279b658531816e7afb98d7aabe89cd1f78f

**Comment by ryanshoover** [comment]
Thanks @jtsternberg and @tw2113!

**Comment by jtsternberg** [comment]
Thank **you**, sir.

**Pull request merged**
