### PR TITLE
#399 Generate RTL Styles for CMB2

### PR DESCRIPTION
**Pull request by devinsays**
Pull request for this ticket: https://github.com/WebDevStudios/CMB2/issues/399

You may want to move the RTL style generation and compression into its own Grunt task (or add to build:i18n). I'm not sure how much extra time it adds if you're running watch, and is probably only necessary on build.

### CODE REVIEW

**Comment by jtsternberg** [comment]
Hey @devinsays, did we get any traction testing this? If not, we may want to just roll it in, and get feedback organically.

**Comment by devinsays** [comment]
I had one person offer to do testing, but they needed me to set up a public dev environment for them so they could look. Just haven't had a chance to do that yet.

A number of people requested this feature. It would be great if @hyyan, @moonman22, @safiro or @adilelsaeed could jump in and test.

https://github.com/WebDevStudios/CMB2/issues/399

However, I think it would be fine to roll and test organically. Any bugs would likely be minor display issues and probably still an upgrade from the current display in RTL languages.

**Comment by wesamly** [comment]
@devinsays How can download the version contains your updates? I started working with CMB2, and I need RTL for Arabic.

**Comment by jtsternberg** [comment]
@wesamly You can download/test the [trunk branch](https://github.com/WebDevStudios/CMB2/tree/trunk).

**Comment by wesamly** [comment]
@jtsternberg Thank you, i'll test and be back with results.

**Comment by wesamly** [comment]
RTL is working great. I tested with Arabic. It will be great if added to master branch. Thank you @jtsternberg  @devinsays 

screen shot 2015-12-08 at 11 59 31 am

**Comment by wesamly** [comment]
Hello,
I noticed that when I used this branch, I get the following error in some pages:
Fatal error: Cannot redeclare cmb2_dir() (previously declared in /Applications/MAMP/htdocs/lab/wptest/wp-content/themes/cpt_theme/cpt_base/library/CMB2/includes/helper-functions.php:18) in /Applications/MAMP/htdocs/lab/wptest/wp-content/plugins/ls_slider/CMB2/includes/helper-functions.php on line 20

But when I use the official branch, it doesn't appear.

I've a plugin that embed CMB2, and I also embed it in a theme.

**Comment by devinsays** [comment]
I think this is fine to merge assuming you're fine with the implementation. We've had at least a few RTL readers sign off on how it works.

I can't reproduce the the declaration issues, and don't see anything in the changeset that would cause a problem like that.

@jtsternberg Let me know if there's anything else you would like me to test, or if a unit test could/should be added here.

**Comment by jtsternberg** [comment]
It is merged (it's in the trunk branch), I just need to take the time to put out a proper release.

**Pull request merged**
