### PR TITLE
Ready for TX - 120 latest langs - new pot - etc...

### PR DESCRIPTION
**Pull request by fxbenard**
You should be ready to speak 120 langs now with some new grunt tasks

Send new GH langs to TX much easier to manage after if you can

See ya

### CODE REVIEW

**Comment by jtsternberg** [comment]
Yowzaz! Thanks a lot @fxbenard!

**Comment by jtsternberg** [comment]
Merged! https://github.com/WebDevStudios/CMB2/commit/39a2042ee69cefdf4d7adadb20f72a3ceaa61226

**Comment by jtsternberg** [comment]
When I try using `grunt tx-push`, I get:
```
Pushing translations for resource cmb2.cmb2:
>> You don't seem to have a proper source file mapping for resource cmb2.cmb2. Try without the --source option or set a source file first and then try again.
```
Any thoughts @fxbenard?

**Comment by fxbenard** [comment]
Just tested it here, working perfectly. Do you have the .tx folder in your local project. 
It's .git ignored. I guess you never created it.

Check it out here: https://github.com/WP-Translations/grunt-transifex-wordpress. Just replace everything with cmb2

**Comment by jtsternberg** [comment]
I did have the .tx folder, but maybe something got messed up. Just updated it w/ your version and is working now.

**Comment by fxbenard** [comment]
Lovely, problem solved - French is 100% ready on TX

**Comment by jtsternberg** [comment]
Awesome! You guys are on it!

**Comment by fxbenard** [comment]
Yes we're and stay tuned we might at some point be even more than on it but "before it". We'll keep in touch #teasing

**Comment by jtsternberg** [comment]
Ha that's awesome! I have no idea how you pull it off, and at no cost, but just want you to know that we really appreciate it!

**Pull request closed without merging**
