### PR TITLE
Add option to use row_classes and row_classes_cb on group field

### PR DESCRIPTION
**Pull request by mattclegg**
ie 'closed' or could add additional styles via callback.

### CODE REVIEW

**Comment by jtsternberg** [comment]
the `'row_classes'` parameter can already accept a callback, but using the `$field_group->row_classes()` method for a group definitely makes sense. Additionally. the `postbox` and `cmb-repeatable-grouping` classes should be added [in the `$conditional_classes` array](https://github.com/mattclegg/CMB2/blob/trunk/includes/CMB2_Field.php#L724-L731).
Please revise your PR.

**Comment by jtsternberg** [comment]
Closing, as this functionality is now included via a group field's 'classes_cb' and 'classes' parameters.

**Comment by miklb** [comment]
@jtsternberg is this documented yet? is the `classess` param the same as for the form?

**Comment by jtsternberg** [comment]
Yep, in https://github.com/WebDevStudios/CMB2/releases/tag/v2.2.2

**Comment by jtsternberg** [comment]
Just updated the docs as well: https://github.com/WebDevStudios/CMB2/wiki/Field-Parameters#classes

**Pull request closed without merging**
