### PR TITLE
Non-Repeatable Groups - Issue/93

### PR DESCRIPTION
**Pull request by marcusbattle**
Hey Justin, here's the updates for issue 93. I'm not sold on the dom and how to modify the CSS so I could use your help there, but the base logic for non-repeatable fields is present.

### CODE REVIEW

**Comment by jtsternberg** [comment]
@marcusbattle can you merge master into your branch as it's pretty far out of date.

**Comment by marcusbattle** [comment]
Sure thing!

**Comment by marcusbattle** [comment]
Hey Justin, my branch has been updated. Let me know if you need anything else.

**Comment by pmgarman** [comment]
I think this could be simplified further looking at it (also just ran into needing a non repeatable group). Passing $repeatable into `render_group_row()` shouldn't be needed since `$field_group` is already being passed and the value can be accessed with `$field_group->args( 'repeatable' )`

**Comment by jtsternberg** [comment]
Finally got this feature merged. I made a few updates/tweaks (things like @pmgarman mentioned). You can see all the changes here: https://github.com/WebDevStudios/CMB2/compare/0d3f70617e71e7a878afefab46a1931a4ea9b9be...8c325372c969487eb24558317c935843da55ac83

**Pull request closed without merging**
